apiVersion: skaffold/v3
kind: Config
metadata:
  name: postgres
deploy:
  helm:
    flags:
      install:
        - --create-namespace
    releases:
      - name: postgresql
        repo: https://charts.bitnami.com/bitnami
        remoteChart: postgresql
        version: 15.5.38
        namespace: daywriter
        setValues:
          global.postgresql.auth.database: datesaver
